### PR TITLE
Bump mastarm to v5.0.2 to resolve security vulnerabilities

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Bump mastarm to [5.0.2](https://github.com/conveyal/mastarm/releases/tag/v5.0.2) to fix vulnerabilities.

### CODE REVIEW

**Comment by landonreed** [comment]
It looks like there are a lot of new flow type issues under mastarm 5.

**Comment by evansiroky** [comment]
What level of effort would it take to fix the flow-type errors? I think we ought to revert the flow upgrade in mastarm if it's too much effort.

**Comment by landonreed** [comment]
@evansiroky, I'm not exactly sure, but basically all of the actions are broken (including some stuff in `flow-typed/redux-actions`). There's a chance that some fix in the flow-typed repo could fix this stuff up, but I haven't really dug in. Let me spend some time with this to see if I can resolve stuff quickly.

**Comment by landonreed** [comment]
Ah, looks like this was due to a change in 0.85 https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8

**Comment by landonreed** [comment]
@evansiroky, I'm not quick enough with absorbing this flow stuff to make it worth our time, so I would say we should bump down to v0.85.0 of flow-bin in mastarm unless you want to take a crack.

**Comment by evansiroky** [comment]
Yeah, let's definitely downgrade flow-bin in mastarm to the latest possible version that still works, but also create an issue to update to the latest flow.

**Comment by landonreed** [comment]
OK, I've got a branch ready to push once I get the correct permissions set by Trevor on mastarm.

**Comment by evansiroky** [comment]
> OK, I've got a branch ready to push once I get the correct permissions set by Trevor on mastarm.

I just made you an admin on mastarm.

**Comment by evansiroky** [comment]
Assigning back to @landonreed to update to latest mastarm.

**Comment by landonreed** [comment]
@evansiroky, I think you mentioned that you might already have fixes for the flow issues here. Is that correct?

**Comment by evansiroky** [comment]
Yep: https://github.com/ibi-group/datatools-ui/commit/a9dec1f9bbac8f520db0e50d792da47029edaada

**Comment by evansiroky** [comment]
Assigning back to Landon so the Travis builds can run properly.

**Comment by landonreed** [comment]
OK, build is complete. Once you add a review, I think we can merge.

**Pull request merged**
