### PR TITLE
Display null continuous_pickup as 1 (no continous pickup)

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Empty values of continuous_pickup and drop_off are misinterpreted by the front end as “0 - Available”. The correct value is 1 - Not Available.

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
> ~@philip-cline Should this change apply to the route editor too?~

Scratch that comment, that attribute is optional in `routes.txt`, but is there a way to make those fields optional in the pattern editor?

**Comment by philip-cline** [comment]
Making the fields optional would also apply then to `pickup_type` and `drop_off_type` which are also optional in the spec. I can take a stab at updating these & also making sure behaviour around the routes.txt continuous pickup and dropoff is working correctly

**Comment by philip-cline** [comment]
> Another (probably important) thing to consider is the spec allows the stop times with unspecified continuous pickup/drop off to "inherit" those the corresponding settings of the parent route (see spec link above).

Yep definitely, although does this mean we would want to display stop_time level continuous_pickup & drop_off as the inherited value, until is overridden? This seems closest to user intention, but would take me more time to implement (so maybe get the correct display out there in this PR, & the inheritance and override in a following PR).

**Comment by binh-dam-ibigroup** [comment]
> > Another (probably important) thing to consider is the spec allows the stop times with unspecified continuous pickup/drop off to "inherit" those the corresponding settings of the parent route (see spec link above).
> 
> Yep definitely, although does this mean we would want to display stop_time level continuous_pickup & drop_off as the inherited value, until is overridden? This seems closest to user intention, but would take me more time to implement (so maybe get the correct display out there in this PR, & the inheritance and override in a following PR).

I am fine with doing that in a separate PR.

**Review by miles-grant-ibigroup — APPROVED** [review]
Patch works great for me thanks!

**Pull request merged**
