### PR TITLE
Make subnet/security group fields optional

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Re #507

### CODE REVIEW

**Comment by landonreed** [comment]
@binh-dam-ibigroup, the user mgt stuff is from another PR that was already merged into dev (I based these changes off of the `dev` branch instead of `otp-deployment-docs-update`). If you merge the latest `dev` into your otp-deployment-docs-update branch and push the changes, those commits should go away from this PR.

The contents of this PR in my view should just be the optional fields and the updates to the docs regarding these fields.

**Comment by evansiroky** [comment]
Should this be a merge to `dev` instead of `otp-deployment-docs-update`?

**Comment by binh-dam-ibigroup** [comment]
> Should this be a merge to `dev` instead of `otp-deployment-docs-update`?

The documentation update goes into the docs branch for #506, I suppose?

**Pull request merged**
