### PR TITLE
Validation issue prioritization

### LINKED ISSUE #477: Indicate validation issue priority in validation table
In the list of validation issues for a given feed version, there is no indication of priority given to the various issue types. In other words, there is no way to distinguish whether an issue could be considered an error vs. a warning -- e.g., something that would break feed ingestion by a third party service vs. just affect how a name field might be rendered.

We already have a measure of priority stored in the gtfs-lib class that deals with validation issues. We just need to display this in the UI using either the binary error vs. warning classification or the multi-tiered priority classification.

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR seeks to fix #477 by modifying the version validation error viewer in two ways:
- it will sort errors based off of priority level and then alphabetically
- it shows different icons based on error severity

This PR depends on the https://github.com/ibi-group/datatools-server/pull/275 PR to datatools-server that uses the version of gtfs-lib that includes the graphQL changes.

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
The way it is depicted in Landon's post might suggest there could be, within one category, there might be critical issues and less critical issues (e.g. 50 critical unused stops and 214 less critical stops).
I would place the icon to the left of the text to avoid that confusion (keep the count to the right).

**Comment by landonreed** [comment]
@binh-dam-ibigroup, I don't 100% follow the comment, but here's what it looks like with the icons on the right. I think it does look better, but I'm not crazy about how this looks. I'm wondering if there's a better way to format all of this.

image

**Comment by evansiroky** [comment]
Other PRs have been merged in. Good to go, @landonreed?

**Pull request merged**
