### PR TITLE
Map

### PR DESCRIPTION
**Pull request by changtung**
I don't know if there are any tests to pass for this app, so if tests are no passing, please let me know about it and ill solve something. 

this branch is functionality that You choose between OSM map and MAPBOX map in env.yml. 
it was done on some older version however i see git shows this can be automatically merged. 
Looking forward for an answer from You:)

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
Thanks for your contribution! The lint step is currently failing but you should be able to fix this by running `yarn lint --fix`. We will take a look at if this implementation is our preferred way of adding this feature. But we agree it's important and thank you again for your fix!

**Comment by changtung** [comment]
fixed with lint. now success.
image

**Comment by changtung** [comment]
IT this E2E test working with auth0 client id and password ? I am asking becuse we do not want to submit those details to github repository. How to ommit this if yes @miles-grant-ibigroup ?

**Comment by miles-grant-ibigroup** [comment]
We use GitHub secrets for these. They only get inserted on PRs we open. We might open a new PR for your branch so that they run. We'll keep you posted! Thanks

**Comment by miles-grant-ibigroup** [comment]
Closed in favor of #931. @changtung please let me know if the new PR works for you!

**Pull request closed without merging**
