### PR TITLE
Remove label if deployment is inactive (ELB test deployment)

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Currently ELB test deployments will maintain their deployment label even after they are inactive. This PR resolves that issue.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
This works for the ec2 case locally. Build-over-wire is tested in the e2e tests, so approved conditional on the e2e tests passing!

**Comment by philip-cline** [comment]
Blocked awaiting e2e test login fix

**Comment by miles-grant-ibigroup** [comment]
e2e tests are passing on this branch!

**Review by daniel-heppner-ibigroup — APPROVED** [review]
lgtm

**Pull request merged**
