### PR TITLE
Mobility data validator 4.1.0

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] e2e tests are all passing _(remove this if not merging to master)_

### Description

Partner PR to https://github.com/ibi-group/datatools-server/pull/560 https://github.com/ibi-group/datatools-server/pull/571

### CODE REVIEW

**Comment by philip-cline** [comment]
Is this ready for review now that https://github.com/ibi-group/datatools-server/pull/571 is unblocked? Or is more work required?

**Review by AdrianaCeric — COMMENTED** [review]
~~Hey could you give me context for some of these changes~~ nm ty Phil

**Review by AdrianaCeric — APPROVED** [review]
Thanks for these changes!

**Review by philip-cline — APPROVED** [review]
LGTM too

**Pull request merged**
