### PR TITLE
fix(gtfs.yml): add more currency types for fares

### LINKED ISSUE #550: Add more currencies for fares
Data Tools UI currently only supports a handful of [currency types](https://en.wikipedia.org/wiki/ISO_4217#Active_codes) (USD, EUR, and GBP). We should add more to cover more transit markets (especially North America).

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

fixes #550 by adding top currencies traded in world (and major North American currency types).

### CODE REVIEW

**Comment by landonreed** [comment]
Yea, perhaps you're right @evansiroky.

**Comment by binh-dam-ibigroup** [comment]
Instead of keying them in manually, can that be retrieved from some other source?

**Comment by landonreed** [comment]
Actually, I'm not really sure including all of them is warranted @evansiroky and @binh-dam-ibigroup. Having hundreds of values really just clutters the dropdown immensely. Sure, specifying some obscure currency is valid, but if our only users of the system are in North America, does it really help to have "Platinum" as a currency type in here?

**Comment by binh-dam-ibigroup** [comment]
I agree with @landonreed, it's fine to key in a few like in this PR, but it doesn't make sense to key in everything, especially if we just copy from some other place.

**Comment by evansiroky** [comment]
I'm still a fan of allowing all possible values. The [GTFS spec is clear](http://gtfs.org/reference/static/#field-types) that any ISO 4217 currency code is a valid value. Since we're making software that produces GTFS feeds I don't think it makes sense to exclude valid possible values. Go ahead and overrule me if you like though.

**Comment by landonreed** [comment]
@evansiroky, how do you propose we hide the values with react-select? I'm open to the idea. Feel free to jump on https://github.com/ibi-group/datatools-ui/pull/566/files.

**Pull request merged**
