### PR TITLE
test(e2e): Fix running e2e tests on dependabot PRs and on push to dev/master

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [na] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

#806 did not end up resulting in automatic triggering of e2e tests for dependabot, so this PR tries to fix that 🫰.
PR also (temporarily) reinstates running e2e tests on pushes to master and dev.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
🫰

**Review by daniel-heppner-ibigroup — APPROVED** [review]
👍

**Comment by binh-dam-ibigroup** [comment]
lol that **still** didn't work to trigger e2e tests with dependabot (see #807 at https://github.com/ibi-group/datatools-ui/runs/7040571200?check_suite_focus=true#step:10:1). My next target is probably going to be that `$GITHUB_REPOSITORY` variable I haven't touched.

**Comment by miles-grant-ibigroup** [comment]
good luck

**Pull request merged**
