### PR TITLE
Update to mastarm 5.3.0

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Updates to the latest mastarm to bring in new features such as announcing deployments to MS Teams.

### CODE REVIEW

**Comment by landonreed** [comment]
Please fix failing CI build.

**Comment by evansiroky** [comment]
I went ahead and fixed the linting errors. It didn't take very long. However, there was an extra configuration setting I needed to change in mastarm. I've made a PR for that over here: https://github.com/conveyal/mastarm/pull/296.

**Comment by evansiroky** [comment]
I'm re-requesting a review from Binh because I had to do one more thing to make the linter happy.

**Pull request merged**
