### PR TITLE
Support MAP_BASE_URL config property

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
- [x] The description lists all relevant PRs included in this release _(remove this if not merging to master)_

### Description

This PR introduces a fully backwards compatible method of avoiding Mapbox. A new `MAP_BASE_URL` config property is added, which allows for not using Mapbox. The attribution can be updated by updating the `MAPBOX_ATTRIBUTION` config property.

Blocked by java 18 fixes in #916

### CODE REVIEW

**Comment by changtung** [comment]
it does work after adding MAP_BASE_URL: http://tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by miles-grant-ibigroup** [comment]
Happy to hear it! Thanks for giving it a try

**Comment by changtung** [comment]
Unfortunately on this version, there is a mistake: 
Zrzut ekranu 2023-03-15 o 12 25 59
- Validation error of type FieldUndefined: Field 'stop_headsign' in type 'patternStop' is undefined @ 'feed/routes/patterns/pattern_stops/stop_headsign' ({"line":46,"column":5})
- its in timetable after choosing line. 
- Could You have look at it or comment? 
I need to mention that our version was created from commit b240cb6f0a8d809f18bae8315a610e8af921ca0a so older one and Your PR may be from newest version? does it make sense?

**Comment by miles-grant-ibigroup** [comment]
This is related to other changes merged into the `dev` branch! You'll need to migrate your database to take advantage of new stop_headsign features. This PR does not cause this problem.

@philip-cline may be able to advise further

**Comment by philip-cline** [comment]
Yep that's correct. That's related to the fact that we added support for `stop_headsigns` recently. Your database does not have the stop_headsign field in the `pattern_stops` table. You'll need to migrate that to remove the error.

**Review by philip-cline — APPROVED** [review]
This is working well for me, I think this is a very sensible addition.

**Review by binh-dam-ibigroup — APPROVED** [review]
LGTM, assuming retina/high-res support on non-mapbox sources will be handled separately.

**Pull request merged**
