### PR TITLE
Release attempt, again...

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Now that #499 is merged into `dev` we should try to an automated release again.

### CODE REVIEW

**Comment by landonreed** [comment]
Travis build appears to be failing.

**Comment by evansiroky** [comment]
Blocked by #585.

**Comment by evansiroky** [comment]
The e2e tests are passing again. Time for a release?

**Pull request merged**
