### PR TITLE
Add Polish Langauge

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR adds a polish language file. Language support is already built into datatools. By default, the browser's language will be detected and the correct language file automatically loaded (see https://github.com/ibi-group/datatools-ui/blob/dev/lib/common/util/config.js#L119)

There is also a redux action (https://github.com/ibi-group/datatools-ui/blob/dev/lib/manager/actions/languages.js#L5) to override the language from the browser, however no UI element takes advantage of this action yet. This is something that can be added in the future should people want to use datatools in a language other than their browser's language.

@wkulesza I've heard you are interested in this -- once this is approved, we'd be able to deploy the state of this PR as-is. If you'd like to add more translation strings, let us know and we'll wait until you're ready to deploy this PR! If you'd like to deploy this now and then deploy a subsequent translation update PR later, this is also an option.

Please let us know what is best for you!

### CODE REVIEW

**Review by binh-dam-ibigroup — COMMENTED** [review]
I defer to @@wkulesza for whether they want to proceed.

**Comment by wkulesza** [comment]
@binh-dam-ibigroup @miles-grant-ibigroup Hi, please do proceed as-is, and then, I will provide more translations and double-check if the previously translated are ok.

**Review by binh-dam-ibigroup — APPROVED** [review]
Approving per @wkulesza's plan for completing the translation as there are quite a bit of English text left.

**Comment by binh-dam-ibigroup** [comment]
@wkulesza For adding translations, I would suggest you submit one or more pull requests with the Polish YML file updated with the suitable text.

**Comment by wkulesza** [comment]
https://github.com/ibi-group/datatools-ui/pull/741

**Review by philip-cline — APPROVED** [review]

**Pull request merged**
