### PR TITLE
Fix exception keys so that values do not reappear on deletion

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Previously, issues with conflicting component keys were causing values to be transferred between exceptions mysteriously on deletion. This PR resolves that issue.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Quick fix love it! Approved provided e2e tests pass once those are fixed

**Comment by philip-cline** [comment]
I'm a little confused why the e2e tests are failing on the CI, they pass locally for me: 
image

**Comment by philip-cline** [comment]
well they're passing now.. the x files theme plays in my head whenever I run these things

**Review by binh-dam-ibigroup — COMMENTED** [review]
I recommend closing this PR and instead addressing the use of keys per https://github.com/ibi-group/datatools-ui/pull/843#pullrequestreview-1099740162.

**Pull request merged**
