### PR TITLE
Release

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] e2e tests are all passing _(remove this if not merging to master)_
- [ ] Code coverage does not significantly worsen (ideally it improves) _(remove this if not merging to master)_

### Description

New version release with the following PRs: #553, #588, #579, #591, #545, #594, #597, #595, #601, #596, #600, #551, #602, #603

### CODE REVIEW

**Comment by landonreed** [comment]
@evansiroky, it looks like the e2e tests are broken again. Any insights? Looks like the OTP router is registered, but the trip could not be planned: https://travis-ci.org/github/ibi-group/datatools-ui/builds/716913172#L1981

**Comment by evansiroky** [comment]
This appears to be happening because of the problem that was fixed in https://github.com/ibi-group/datatools-server/pull/334. That PR was merged into the branch that https://github.com/ibi-group/datatools-server/pull/331 is using, so once that gets merged into dev, these e2e tests should start passing again.

**Comment by evansiroky** [comment]
Blocked until https://github.com/ibi-group/datatools-server/pull/336 is merged and a new jar is uploaded.

**Comment by evansiroky** [comment]
Test are passing again. Unblocking.

**Review by binh-dam-ibigroup — APPROVED** [review]

**Pull request merged**
