### PR TITLE
Docs: Adjust Deployment

### PR DESCRIPTION
**Pull request by dancesWithCycles**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

Hi folks,
This PR seeks to adjust the [deployment](https://github.com/ibi-group/datatools-ui/blob/dev/docs/dev/deployment.md) file and to solve at least issue #770. Please feel free to use, study, share or improve the PR.

Cheers!

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Thanks very much for making these changes! These updates should really help in setting datatools up, which is a process I've wanted to make easier for a while now.

Hope things with datatools have been going alright otherwise!

**Comment by dancesWithCycles** [comment]
> Thanks very much for making these changes! These updates should really help in setting datatools up, which is a process I've wanted to make easier for a while now.
> 
> Hope things with datatools have been going alright otherwise!

Hi @miles-grant-ibigroup ,
Helping makes me happy. I  could not setup an instance of datatools yet, though I want it very badly. I have no experiene with Auth0 and need extra help or time to set it up. My favorite would be an datatools branch without Auth0 or user management via Posqres.

Cheers!

**Comment by miles-grant-ibigroup** [comment]
I think our preference is not to maintain another branch, but feel free to fork! 

There is a `DISABLE_AUTH` config setting that is supposed to entirely disable everything related to auth0. Unfortunately, it hasn't worked in years. However, I believe this is the approach to take and it should just be a matter of short circuiting a few auth0 api wrapper methods!

**Review by binh-dam-ibigroup — APPROVED** [review]
Thanks for offering these changes!

**Comment by miles-grant-ibigroup** [comment]
Once #777 is merged into dev and dev merged into this one this PR will be ready for merge!

**Comment by miles-grant-ibigroup** [comment]
@dancesWithCycles if you merge dev into this branch the unit tests should pass and we can then merge! Thanks again for your PR

**Comment by dancesWithCycles** [comment]
> @dancesWithCycles if you merge dev into this branch the unit tests should pass and we can then merge! Thanks again for your PR

Hi @miles-grant-ibigroup ,
Mission completed! Please feel free to use, study, share and improve this PR.

Cheers!

**Pull request merged**
