### PR TITLE
ci(e2e): Run e2e tests on dependabot PR branches.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [na] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [na] All tests and CI builds passing

### Description

This PR changes a condition so that e2e tests will be run for PRs created by dependabot.
This will facilitate accepting security-related PRs.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Do we not want to run the e2e tests on every commit?

**Comment by binh-dam-ibigroup** [comment]
> Do we not want to run the e2e tests on every commit?

@miles-grant-ibigroup I believe dependabot creates a single commit per PR most of the time.

**Comment by miles-grant-ibigroup** [comment]
I meant do we not want to enable the e2e tests for all our commits as well -- I don't think there are any large compute costs involved right?

**Comment by binh-dam-ibigroup** [comment]
> I meant do we not want to enable the e2e tests for all our commits as well -- I don't think there are any large compute costs involved right?

e2e tests are compute intensive. On CI they take about 15 mins.

**Comment by miles-grant-ibigroup** [comment]
OTP-UI tests take about 10 minutes, but if that's too much for us here I don't mind keeping the tests `dev`-only!

**Review by daniel-heppner-ibigroup — APPROVED** [review]

**Pull request merged**
