### PR TITLE
ci(e2e): Run e2e on approved PRs

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [na] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Screen Shot 2022-07-14 at 6 21 39 PM

Maybe this is a good middle ground. This PR does the following:
- Runs "basic" tests on all pushes
- Changes the test that is run on pull request updates, so that it runs e2e tests, but only under the conditions in the pull request workflow (~PR review requested, PR is in an approved state~ non-draft PRs, dependabot PR, PR to master), otherwise it will appear as "Skipped". If in a "skipped" state, PR approval is required, then the check will have to be re-run manually, or by pushing a commit to the PR branch.

In the end, regular tests are ran only once per commit, and e2e tests are "visually required" to run upon approval.
Passing e2e tests can be made required for merging after this PR is approved.

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
@miles-grant-ibigroup Looking for feedback around the "milestones" that would require running e2e tests.

**Review by miles-grant-ibigroup — APPROVED** [review]
On paper this looks much better than the previous way of doing things and doing it all through Github actions feels much better too! 

I don't think I can comment on the workflow until we use this one for a few PRs. For now, this PR looks excellent thanks for all the research that this PR must have required!

**Comment by miles-grant-ibigroup** [comment]
I should note I received a failure email after approving... that's strange. Says that no tests were run, but isn't that expected? Weird

**Comment by binh-dam-ibigroup** [comment]
> I should note I received a failure email after approving... that's strange. Says that no tests were run, but isn't that expected? Weird

That's the problem, we don't really know if the things work until they run.

**Comment by miles-grant-ibigroup** [comment]
For now, I think what you have here is quite reasonable

**Review by daniel-heppner-ibigroup — APPROVED** [review]
LGTM, may as well try it out!

**Comment by binh-dam-ibigroup** [comment]
> LGTM, may as well try it out!

Interesting, the second approval did not trigger the e2e run as intended...

**Comment by binh-dam-ibigroup** [comment]
> > LGTM, may as well try it out!
> 
> Interesting, the second approval did not trigger the e2e run as intended...

Actually it did (see https://github.com/ibi-group/datatools-ui/actions/runs/2779781776) but an error occured!

**Comment by binh-dam-ibigroup** [comment]
Per discussion, https://github.com/ibi-group/datatools-ui/pull/818/commits/c4d48183e58ae6e0b4290dc18d02d28faa69071a changes the behavior to run e2e tests on non-draft PRs. So going forward after this is merged, to skip e2e tests, place your PR in a draft state. Also, as a general rule, to skip all github actions, add `[skip ci]` to the corresponding commit.

**Pull request merged**
